# **Question:**
Part 1: Loss

1. Implement a function to calculate the mean squared error (MSE) loss given the predicted values and the true values.


2. Implement a function to calculate the mean absolute error (MAE) loss given the predicted values and the true values.


3. Implement a function to calculate the Huber loss given the predicted values, true values, and a parameter delta.


Part 2: Estimating Model Parameters

1. Implement a function to estimate the parameters of a linear regression model using the ordinary least squares (OLS) method.

Part 3: Properties of Fitted Values

1. Implement a function to calculate the fitted values given the feature matrix and the estimated model parameters.


2. Implement a function to calculate the residuals given the observed values and the fitted values.


In [ ]:
pip install numpy pandas matplotlib scikit-learn jupyter

In [ ]:
pip install tensorflow

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
url = "/content/drive/MyDrive/Colab Notebooks/data.csv"
data = pd.read_csv(url)

In [ ]:
drop = ['Price', 'Location']
X = data.drop(columns = drop, axis = 1)

y = data['Price']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

**Estimating Model Parameters:**

In [ ]:
# OLS Method:
matrix_X = X.values
print(matrix_X.shape)

(6207, 38)


In [ ]:
vector_y = y.values
print(vector_y.shape)

(6207,)


In [ ]:
transpose_X = tf.transpose(X)
print(transpose_X)

tf.Tensor(
[[3340 1045 1179 ... 1143 1680 1162]
 [   4    2    2 ...    2    3    2]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    9    9    9]
 [   0    0    0 ...    9    9    9]
 [   0    0    0 ...    9    9    9]], shape=(38, 6207), dtype=int64)


In [ ]:
input_matrix = tf.matmul(transpose_X, X)
print(input_matrix)

tf.Tensor(
[[18086317933    26636338      773600 ...    59087153    58639734
     59087153]
 [   26636338       43573        1232 ...       99058       98379
        99058]
 [     773600        1232         489 ...        2785        2781
         2785]
 ...
 [   59087153       99058        2785 ...      344981      344736
       344981]
 [   58639734       98379        2781 ...      344736      344736
       344736]
 [   59087153       99058        2785 ...      344981      344736
       344981]], shape=(38, 38), dtype=int64)


In [ ]:
print(input_matrix)

tf.Tensor(
[[18086317933    26636338      773600 ...    59087153    58639734
     59087153]
 [   26636338       43573        1232 ...       99058       98379
        99058]
 [     773600        1232         489 ...        2785        2781
         2785]
 ...
 [   59087153       99058        2785 ...      344981      344736
       344981]
 [   58639734       98379        2781 ...      344736      344736
       344736]
 [   59087153       99058        2785 ...      344981      344736
       344981]], shape=(38, 38), dtype=int64)


In [ ]:
input_matrix = tf.cast(input_matrix, dtype = tf.float64)

In [ ]:
inverse_input = tf.linalg.pinv(input_matrix)

In [ ]:
inverse_input = inverse_input.numpy()

In [ ]:
print(inverse_input)

[[ 6.12064555e-10 -4.74342616e-07 -7.17085258e-08 ...  3.08578118e-08
  -8.91590446e-08  3.08578118e-08]
 [-4.74342616e-07  6.78352684e-04  4.54402821e-05 ... -1.48453687e-06
   5.49923757e-04 -1.48453687e-06]
 [-7.17085248e-08  4.54402805e-05  2.77051088e-03 ... -3.92605527e-05
  -2.34985692e-04 -3.92605527e-05]
 ...
 [ 3.08578125e-08 -1.48453761e-06 -3.92605523e-05 ...  1.03672950e-02
  -2.41132602e-04  1.03672950e-02]
 [-8.91590488e-08  5.49923761e-04 -2.34985693e-04 ... -2.41132602e-04
   1.14738060e-02 -2.41132602e-04]
 [ 3.08578125e-08 -1.48453761e-06 -3.92605523e-05 ...  1.03672950e-02
  -2.41132602e-04  1.03672950e-02]]


In [ ]:
inverse_input = tf.cast(inverse_input, dtype = tf.float64)
transpose_X = tf.cast(transpose_X, dtype = tf.float64)
theta_0 = tf.matmul(inverse_input, transpose_X)

In [ ]:
y = tf.cast(y, dtype = tf.float64)
y = np.expand_dims(y, axis = -1)
print(y.shape)

(6207, 1)


In [ ]:
theta = tf.matmul(theta_0, y)

In [ ]:
print(theta)

tf.Tensor(
[[    8599.86511461]
 [-2512967.31705383]
 [-2371194.34815312]
 [-1976326.98982114]
 [  167200.96029656]
 [ 3457983.0897926 ]
 [-5691740.99143334]
 [ 2668732.9442288 ]
 [ 3993789.46967183]
 [  921351.41716918]
 [  889167.39906062]
 [  -55114.08551872]
 [ 2348946.56168047]
 [-2059236.20457837]
 [  -86612.43932052]
 [-3461104.12296267]
 [  971384.63142269]
 [ 1252450.46359704]
 [ 3046304.61458352]
 [ -171815.27462772]
 [ -595889.61739281]
 [-2054609.99819901]
 [  381061.01191061]
 [  279670.48189868]
 [ -147252.92607657]
 [ 1097186.25447026]
 [ -473083.8169699 ]
 [  -64027.58928633]
 [-3215117.134045  ]
 [ -956647.69503308]
 [-1899933.04753773]
 [  279670.48190402]
 [  989758.42235616]
 [  279670.481901  ]
 [  279670.481901  ]
 [  279670.481901  ]
 [ -473083.81696953]
 [  279670.48190029]], shape=(38, 1), dtype=float64)
